apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-mcp-server
  labels:
    app: elasticsearch-mcp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch-mcp-server
  template:
    metadata:
      labels:
        app: elasticsearch-mcp-server
    spec:
      containers:
      - name: elasticsearch-mcp-server
        image: your-registry/elasticsearch-mcp-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: CONTAINER_MODE
          value: "true"
        - name: HTTP_ADDRESS
          value: "0.0.0.0:8080"
        - name: ES_URL
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: es-url
        - name: ES_API_KEY
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: es-api-key
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-mcp-server-service
spec:
  selector:
    app: elasticsearch-mcp-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
type: Opaque
stringData:
  es-url: "https://otel-demo-a5630c.kb.us-east-1.aws.elastic.cloud"
  es-api-key: "YOUR_API_KEY_HERE"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-mcp-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - mcp.yourdomain.com
    secretName: elasticsearch-mcp-server-tls
  rules:
  - host: mcp.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch-mcp-server-service
            port:
              number: 80
